print("Hello World!")
print('Я', 'учусь', 'программировать', 'на', 'Python!')

print('Какой хороший день!')
# Команда print() с пустым списком аргументов просто вставляет новую пустую строку.
print()
print('Работать мне не лень!')

print('В тексте есть "двойные" кавычки')
print("В тексте есть 'одинарные' кавычки")
print("I'm", 'the', "BAD", 'guy')
print("Hello, it's me!")
print('Hello, it\'s me!')
print("Здравствуй, мир!")
print("4", "8", "15", "16", "23", "42")
print("4")
print("8")
print("15")
print("16")
print("23")
print("42")
print("4", "\n8", "\n15", "\n16", "\n23", "\n42")
print("*")
print("**")
print("***")
print("****")
print("*****")
print("******")
print("*******")
